In [4]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy

# Restart Kernel After Installation Finish

  Cache entry deserialization failed, entry ignored
    100% |████████████████████████████████| 13.4MB 91kB/s eta 0:00:01   11% |███▌                            | 1.5MB 85kB/s eta 0:02:19


## Numpy

In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4])

In [3]:
np1

array([1, 2, 3, 4])

In [4]:
type(np1)

numpy.ndarray

In [6]:
Mat1 = np.array([[1,2],[3,4]])

In [7]:
Mat1

array([[1, 2],
       [3, 4]])

In [8]:
np1.shape

(4,)

In [9]:
Mat1.shape

(2, 2)

In [10]:
Mat1.dtype

dtype('int64')

In [12]:
Mat1[0,0] = 5

In [13]:
Mat1

array([[5, 2],
       [3, 4]])

In [14]:
Mat1[0,0] = "String" #will error

ValueError: invalid literal for int() with base 10: 'String'

In [29]:
Mat2 = np.arange(0,10,1)

# start from 0, element value max 10 with step 1.

In [30]:
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
Mat3 = np.linspace(0,10,20)

# start from 0, with maximum value 10 with 20 size matrix.
# The step will be adjusted based on the criteria

In [32]:
Mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [33]:
Mat3.shape

(20,)

In [34]:
Mat4 = np.random.rand(5,5)

In [36]:
Mat4

array([[0.64591972, 0.17831329, 0.93509772, 0.92238182, 0.3773564 ],
       [0.03757267, 0.08518854, 0.2129554 , 0.76096555, 0.24702479],
       [0.5411769 , 0.08267035, 0.90251419, 0.73284763, 0.82001528],
       [0.84395186, 0.20966335, 0.18320905, 0.56282917, 0.92430958],
       [0.28222821, 0.75879099, 0.27853665, 0.08113944, 0.02808692]])

In [37]:
Mat5 = np.random.randn(5,5) #normally distributed

In [38]:
Mat5

array([[ 0.14186176,  0.04236006,  0.38888231,  0.68969595, -0.39615384],
       [-0.31497176,  1.85622327, -2.36571625, -1.79957477,  0.86051898],
       [-0.48141238, -1.53103162, -0.15841052, -0.55290313,  0.40622906],
       [ 0.47924755,  2.43276616, -0.37605234, -0.96522998, -0.28469958],
       [-0.96155972, -0.43634883,  0.31629188, -1.43154323, -0.6067117 ]])

Another available method:
* np.diag
* np.zeros
* np.ones

In [39]:
Mat5[0,0]

0.1418617607368141

In [43]:
Mat5[0:3,:]

array([[ 0.14186176,  0.04236006,  0.38888231,  0.68969595, -0.39615384],
       [-0.31497176,  1.85622327, -2.36571625, -1.79957477,  0.86051898],
       [-0.48141238, -1.53103162, -0.15841052, -0.55290313,  0.40622906]])